### ISSUE TITLE
Re-add all of the benchmarking and recursive verification code in #40

### ISSUE THREAD

**Issue by jadwahab** [libsv/go-bc#45]
Re-add all of the benchmarking and recursive verification code in #40 - for some reason we never merged that PR in but it was extremely valuable. Maybe just remove all of the cornflakes stuff haha

**Comment by sirdeggen** [comment]
Keeping the Cerealization puns but can delete all this once BRC-61 and [BRC-62](https://brc.dev/62) are implemented in its place.
